name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          if [ -z "${{ secrets.SSH_PORT }}" ]; then
            ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          else
            ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          fi

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT || '22' }}
          key: ${{ secrets.SSH_KEY }}
          envs: SUDO_PASSWORD
          script: |
            echo "[GH-Actions] Start deploy"
            /srv/clash-dual/scripts/deploy.sh
            echo "[GH-Actions] Deploy finished"

